services:
  traefik:
    image: traefik:v3
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --certificatesresolvers.le.acme.email=me@torinasakura.name
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --accesslog
      - --log.level=DEBUG
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      traefik-wp:
        ipv4_address: 172.16.233.99

  wordpress-db:
    image: mariadb:latest
    volumes:
      - ./.data/mysql:/var/lib/mysql
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
      - MYSQL_DATABASE=wordpress
      - MYSQL_PASSWORD=password
      - MYSQL_USER=wordpress
    networks:
      - traefik-wp

  wordpress-fpm:
    build: ./config
    command: bash -c 'install_wordpress && docker-entrypoint.sh php-fpm'
    user: www-data
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_URL: https://wp.local.torinasakura.dev
      WORDPRESS_PREVIEW_URL: https://preview.wp.local.torinasakura.dev
      WORDPRESS_TITLE: Project starter
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: password
      WORDPRESS_ADMIN_EMAIL: admin@example.com
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress-db
    networks:
      - traefik-wp

  wordpress:
    image: nginx:latest
    volumes:
      - ./wordpress:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`wp.local.torinasakura.dev`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      - traefik
      - wordpress-fpm
    networks:
      - traefik-wp

networks:
  traefik-wp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.233.0/24
