name: Bump

on:
  pull_request:
    types: [closed]
    branches:
      - master
  workflow_dispatch:


jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Bump versions
        run: node ./.config/bump/script.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore(common): versions'
          branch: master
